### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by stianjensen** [jazzband/django-hosts#134]
Will there be a new release any time soon?

I see that several deprecation warnings from Django are already fixed on master, and will be needed before Django 4 is released in December this year.

**Comment by stianjensen** [comment]
Django 4.0 is released today, and the latest django-hosts release does not support it (but the issues are fixed on master).

**Comment by gaige** [comment]
@timgraham Not sure if this made it to your radar, but Django 4.0 is now out, and these changes are necessary for compatibility.

**Comment by timgraham** [comment]
A PR similar to https://github.com/jazzband/django-hosts/commit/55634e5dd5cce33619dcb641c5e3c6a9c85e7caa is needed.

**Comment by stianjensen** [comment]
Created one: https://github.com/jazzband/django-hosts/pull/140

**Comment by timgraham** [comment]
django-hosts 5.0 is on PyPI.
