### ISSUE TITLE
new project lead needed

### ISSUE THREAD

**Issue by timgraham** [jazzband/django-hosts#144]
I'm the only [project lead](https://jazzband.co/about/releases#security) here, but I only had an interest in this project because I was paid as a Django fellow to be a maintainer of djangoproject.com which uses django-hosts. I would like to step down if we can find one or more new leaders.

**Comment by hramezani** [comment]
I can help as a lead of this project.
@jezdez Could you consider me as a lead for this project?

**Comment by jezdez** [comment]
@timgraham Thank you for your help with this over the years <3

@hramezani Thank you for volunteering!
