### ISSUE TITLE
Problems with subdomains served by nginx

### ISSUE THREAD

**Issue by ctrlmaniac** [jazzband/django-hosts#146]
I have problem with static and media sites which are served by two different subdomains with nginx.
However I can't reach them because django always displays the default host!

settings.py
```
ROOT_HOSTCONF = "webapp.hosts"
DEFAULT_HOST = "www"
ROOT_URLCONF = "www.urls"
```

hosts.py
```
from django.conf import settings
from django_hosts import host, patterns

host_patterns = patterns(
    "",
    host(r"www", settings.ROOT_URLCONF, name="www"),
    host(r"api", "api.urls", name="api"),
    host(r"admin", "webapp.urls", name="admin"),
)
```

Is it possible to ignore **media** and **static** subdomain?

**Comment by ddabble** [comment]
This sounds like an issue with your Nginx configuration (assuming that Nginx passes requests to your Django server). I happen to know (some of) the basics of configuring an Nginx server, so if you want, it could be helpful if you posted the config code here 🙂 Do you have separate server blocks for the Django server and the `media` and `static` subdomains, and do the server block(s) for those subdomains have `server_name`s that do not overlap with the one of the server block for your Django server?

**Comment by ctrlmaniac** [comment]
I resolved by serving static and media files with the main domain
