### ISSUE TITLE
Apache Configuration -  Directing Multiple subdomains to single wsgi

### ISSUE THREAD

**Issue by michaelwpeck** [jazzband/django-hosts#147]
Could anyone who has set this up with Apache provide an example of their config file?

Do you create multiple linked VirtualHosts and point them both to the same wsgi.py file? If so, does that create any issues?

Thank you!

**Comment by michaelwpeck** [comment]
Just bumping this. Is creating a symlink to 'duplicate' the wsgi file a viable option?

**Comment by michaelwpeck** [comment]
Figured out the issue. Had to set ServerAlias in Apache.

**Comment by ddabble** [comment]
Closing this, as it seems the issue has been resolved. Please reopen it if that's not the case 😊
