### ISSUE TITLE
Error django-hosts and locale

### ISSUE THREAD

**Issue by IMOWWW** [jazzband/django-hosts#155]
```python
from django.conf import settings
from django_hosts import patterns, host
from django.contrib import admin

host_patterns = patterns('',
    host(r'',settings.ROOT_URLCONF, name='root'),
    host(r'www', settings.ROOT_URLCONF, name='wwwroot'),
    host(r'admin', admin.site.urls , name='admin')
)
```

```
ERROR 2023-01-24 01:26:43,572 log 129318 140684844363776 Internal Server Error: /
Traceback (most recent call last):
  File "/home/ilya/imowww/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ilya/imowww/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/home/ilya/imowww/venv/lib/python3.10/site-packages/django/middleware/locale.py", line 24, in process_request
    ) = is_language_prefix_patterns_used(urlconf)
TypeError: unhashable type: 'list'
```

This error occurs when adding admin panel

**Comment by hramezani** [comment]
Could you please provide more information?

- Django version
- Django-host version
- When do you get this error? in the console when you run the server? or somewhere else?

**Comment by IMOWWW** [comment]
this error was fixed by creating another routing file
Example:
from django.conf import settings
from django_hosts import patterns, host
from django.contrib import admin



host_patterns = patterns('',
    host(r'',settings.ROOT_URLCONF, name='root'),
    host(r'www', settings.ROOT_URLCONF, name='wwwroot'),
    host(r'admin', 'imowww.admin_urls' , name='admin')
)


admin_urls.py

from django.urls import path
from django.contrib import admin


urlpatterns = [
    path('', admin.site.urls),
]
