### ISSUE TITLE
Update for removal of add_to_builtins() in Django 1.9

### ISSUE THREAD

**Issue by timgraham** [jazzband/django-hosts#40]
Django 1.9 removes `django.template.base.add_to_builtins()` in favor of [a formalized API](https://docs.djangoproject.com/en/dev/releases/1.9/#django-template-base-add-to-builtins-is-removed).

To ease the migration, in `AppConfig.ready()` we could throw an error if `settings.HOST_OVERRIDE_URL_TAG=True` and  `add_to_builtins` isn't importable (Django 1.9+). The error would inform the user to add `'django_hosts.templatetags.hosts_override'` to the `TEMPLATES['OPTIONS']['builtins']` setting. I think it's probably better than updating the `TEMPLATES` automatically. This approach would allow us to eventually remove `settings.HOST_OVERRIDE_URL_TAG` too.

This would require removing `HOST_OVERRIDE_URL_TAG=True` from settings in order to silence the upgrade error then -- is it okay? I think most projects (not reuseable apps) don't try to support multiple versions of Django at once. If we need to be able to define one settings file that works with multiple versions of Django, then we'll need a different approach.

**Comment by onekiloparsec** [comment]
Looks good. You make a pull-request?

**Comment by timgraham** [comment]
Work in progress is up at https://github.com/jezdez/django-hosts/pull/41.

**Comment by timgraham** [comment]
Pull request is merged.
