### ISSUE TITLE
What about a new release?

### ISSUE THREAD

**Issue by aalebedev** [jazzband/django-hosts#42]
Hi! I'm not sure if it's a right place for my question. Sorry about that. May, 6 - It was so long ago. Now, I get warnings in django 1.8. At the same time, master branch contains some commits fixing these warnings.

**Comment by timgraham** [comment]
I think we'll have a release once Django 1.9 is supported: https://github.com/jezdez/django-hosts/pull/41. There hasn't been a whole lot since then.

**Comment by beaugunderson** [comment]
Also waiting on a release to upgrade to 1.9.

**Comment by jezdez** [comment]
FYI I've moved the repo into the [Jazzband](https://jazzband.co/) organization and hooked it to do auto-releases to PyPI when pushing a new git tag. Releases are now self-service basically.
