### ISSUE TITLE
Support for django1.9?

### ISSUE THREAD

**Issue by altryne** [jazzband/django-hosts#46]
Trying to upgrade to django 1.9 today and it seems like django-hosts is the culprit of this : 

```
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

When I remove `django-hosts` from INSTALLED_APPS this stops showing up

**Comment by bak1an** [comment]
Hi @altryne 

It seems that django 1.9 support is merged into master already but is not yet released to pypi.

I guess that it going to be there soon.

**Comment by altryne** [comment]
Hey @bak1an , thanx for responding. Do you have any knowledge as to how this might appear in pypi? what's the process? 
Will another version need to be released or anything?

I'm specificaly interested to understand if we can continue working on django1.9 migration and use the master of django-hosts for now, and then before the switch we'll update it from pypi?

**Comment by bak1an** [comment]
@altryne 

Please try version 1.3 from pypi, it has just landed there.

You can also install the dependencies directly from their git repositories (and other non-pypi places) - https://pip.pypa.io/en/stable/reference/pip_install/#git

Closing the issue for now, feel free to reopen in case there are any troubles.

**Comment by altryne** [comment]
@bak1an Thank you for being super responsive!
