### ISSUE TITLE
host_url template tag deprecation warning for "on" keyword isn't raised correctly

### ISSUE THREAD

**Issue by timgraham** [jazzband/django-hosts#51]
A warning is raised even if the url tag is used without "on", e.g. `{% url 'homepage' %}` (which relies on the `settings.DEFAULT_HOST`.

Also [the message](https://github.com/jazzband/django-hosts/blob/4b84fa58faac109cd845166b7cf9bf9cab821b08/django_hosts/templatetags/hosts.py#L142-L145) contains an uninterpolated %s, "The 'on' keyword of the '%s' template tag is pending deprecation...".

**Comment by timgraham** [comment]
Rather than spend time trying to fix this, I'd like to just remove it: https://github.com/jazzband/django-hosts/pull/52.

**Comment by jezdez** [comment]
+1

**Comment by jezdez** [comment]
Merged in #52.
