### ISSUE TITLE
Document how to build the docs

### ISSUE THREAD

**Issue by timgraham** [jazzband/django-hosts#53]
`make html` gives `DistributionNotFound: django-hosts` (even after `pip install -e django-hosts`)

`PYTHONPATH=.. make html` gives `ImportError: No module named django.conf`

Are things somewhat broken in the current state or a I missing something?

**Comment by jezdez** [comment]
Fair enough, RTD is set up to install `docs/requirements.txt` and django-hosts itself. That will make sure autodoc works in https://github.com/jazzband/django-hosts/blob/master/docs/reference.rst. Where do you suggest to document this?

**Comment by timgraham** [comment]
Assuming we don't want a separate page in the docs, maybe `CONTRIBUTING.md`?

**Comment by jezdez** [comment]
@timgraham There was indeed a problem with the settings path btw, good catch.
