### ISSUE TITLE
can i use parameter

### ISSUE THREAD

**Issue by SolarisYan** [jazzband/django-hosts#54]
Hello,i use django-host in this case:

    {% for action in actions_list %}
    <li>
        <a href="{% url  action.url_alias %}">{{ action.name_short }}</a>
    </li>
    {% endfor %}

and it error:

Reverse for ''user-edit' 1 host 'account'' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []

how can i solve this problem? any one help?

**Comment by timgraham** [comment]
This is the bug tracker for the project. Please use the [django-users](https://groups.google.com/forum/#!forum/django-users) mailing list for usage questions.
