### ISSUE TITLE
url_name and host_name in host_url template tag as template variable

### ISSUE THREAD

**Issue by SolarisYan** [jazzband/django-hosts#55]
Is it possible to pass url_name and host_name and the parameters as template variable?

i use database to store the variable, and in temple like this:
{% for action in actions_list %}
<li>
    <a href="{% url  action.url_alias %}">{{ action.name_short }}</a>
</li>
{% endfor %}

the action.url_alias is like this  'user-edit' 1 host 'account'

but it error:

Reverse for ''user-edit' 1 host 'account'' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []

how can i solve this problem? any one help?

any help? thanks a lot

**Comment by timgraham** [comment]
This is the bug tracker for the project. Please use the [django-users](https://groups.google.com/forum/#!forum/django-users) mailing list for usage questions.
