### ISSUE TITLE
Retry the 2.0 release

### ISSUE THREAD

**Issue by timgraham** [jazzband/django-hosts#61]
I tried to release 2.0 today but uploading to PyPI failed because the "Framework :: Django :: 1.10" classifier doesn't exist yet. After that's resolved, what do you think is the best way to retry the release? I thought of deleting and recreating the tag -- not sure if that might have some undesired side effect.

**Comment by jezdez** [comment]
Dang, I'm sorry I missed this, glad you were able to figure this out.
