### ISSUE TITLE
what is the  DEFAULT_HOST?

### ISSUE THREAD

**Issue by wkatios** [jazzband/django-hosts#70]
could anyone get me DEMO?

**Comment by asantoni** [comment]
The docs say "Set the DEFAULT_HOST setting to the **name** of the host pattern you want to refer to as the default pattern. It’ll be used if no other pattern matches or you don’t give a name to the host_url template tag."

So, for the example in the documentation:
```
host_patterns = patterns('path.to',
    host(r'api', 'api.urls', name='api'),
    host(r'beta', 'beta.urls', name='beta'),
)
```
You could set `DEFAULT_HOST = 'api'` or `DEFAULT_HOST='beta'`.

(I agree it's a bit confusing - I thought DEFAULT_HOST meant a real hostname at first too.)

**Comment by wkatios** [comment]
Thanks！！！
