### ISSUE TITLE
Slow requests

### ISSUE THREAD

**Issue by Almaral-Engineering** [jazzband/django-hosts#79]
After I added django-hosts the requests started to be slower, it takes some seconds to get the response, before it was almost instantly

**Comment by bartlomieju** [comment]
Are you talking about slow operation on Mac os? I had similar idea changing local domain from `.local` and `.localhost` to something else (like `.foobar`)

**Comment by Almaral-Engineering** [comment]
Yes, it´s no Mac os, I am going to try that and let you know what happens, thanks

**Comment by timgraham** [comment]
If you find that django-hosts is at fault, please reopen with an explanation.
