### ISSUE TITLE
Not Working With Django's Default Authentication

### ISSUE THREAD

**Issue by bobozar** [jazzband/django-hosts#82]
Everything is working fine except for the fact that django_hosts is not working with Django Authentication.

I hosted this url api.example.com so on this page with the url api.example.com:8000/add_post, I want users to add post but before doing that you must be authenticated. So after I logged in, I still can't via the form talkless of posting. But when I go back to example.com, it shows that I'm logged in but api.example.com is telling me otherwise. 

How do I make django authentication work with this package?

**Comment by timgraham** [comment]
Usage questions aren't answered on the issue tracker.

**Comment by ChanceHerriage** [comment]
Would be nice to have an answer to this though.

There aren't any errors being thrown, there aren't any messages. login() of django.contrib.auth even processes successfully, but upon redirect after logging in, there still isn't any user actually logged in.
