### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jasonhoward64** [jazzband/django-hosts#86]
I'm getting the following error when I try to runserver. 

ModuleNotFoundError: No module named 'django_hosts.middleware.HostsRequestMiddlewaremultipledomain'; 'django_hosts.middleware' is not a package

**Comment by fanckush** [comment]
Did you put the middleware in the correct order like instructed?

**Comment by jasonhoward64** [comment]
Yes

**Comment by jasonhoward64** [comment]
It's all good. I was able to write my own middleware to handle subdomains. Thanks though!

**Comment by bastianwegge** [comment]
Sorry to "revive" this very old issue. It actually arises if you forget to put a comma at the end of the line inside the list of middlewares. Just for anybody coming here seeing this :).

Thank you for this awesome package!
