### ISSUE TITLE
Testing Redirects

### ISSUE THREAD

**Issue by coler-j** [jazzband/django-hosts#94]
How do you use `django-hosts` and also use `assertRedirects`?

For example in the following test:

```
class SomeTest(TestCase):
    def test_redirects_to_correct_REDIRECT_URL_on_login(self):
        response = self.client.post(self.login_view, data={'username': self.user.username,
                                                                    'password': USER_DEFAULT_PASSWORD},
                                    follow=True)
        self.assertRedirects(response, reverse('page_to_redirect_to'))
```

I will get a fail as the response will have an expected relative url of `/page-to-redirect-to/` but my reversed url will include the host `//my-host/page-to-redirect-to/`

**Comment by anuj9196** [comment]
@coler-j were you able to resolve it?

**Comment by coler-j** [comment]
@anuj9196 I am thinking that I did not sorry, this was a while ago.
