### ISSUE TITLE
LOGIN_URL giving error when using django.urls.reverse_lazy

### ISSUE THREAD

**Issue by Alexmhack** [jazzband/django-hosts#96]
I am trying to use **LOGIN_URL** with `django.urls.reverse_lazy` in **settings.py** file along with **django_hosts** installed and configured but it gives errors when using a view `@login_required` decorator or `LoginRequiredMixin`.

It gives error that `no reverseMatch found for 'login'` and also we cannot use the `django_host.resolvers.reverse` in the **settings.py** file since it gives error that `apps aren't installed yet`, we only need to use the hard coded url like `LOGIN_URL = //localhost:8000/login/`.

Is there any workaround for this thing instead of using the hard coded urls?

**Comment by markusdosch** [comment]
If anyone reads this now. A solution is to use the lazy version, e.g. like this:

```python
# settings.py
from django_hosts.resolvers import reverse_lazy

LOGIN_URL = reverse_lazy("login", host="www"`)
```
