### ISSUE TITLE
DEFAULT_HOST to no subdomain

### ISSUE THREAD

**Issue by anuj9196** [jazzband/django-hosts#97]
Say I have the domain `example.com`

I want to serve in three ways

1. API
2. Admin
3. Website

```
host_patterns = patterns(
    '',
    host(r'api', api_urls, name='api'),
    host(r'admin', admin.site.urls, name='admin'),
    host(r'', settings.ROOT_URLCONF, name='root')
)
```
The website will have no subdomain configured and the default will be the website and thus want to setup in settings like
```
ROOT_HOSTCONF = 'app.hosts'
DEFAULT_HOST = ''
```

I tried this but not working.

**Comment by cobang** [comment]
I think, the `name` of the host pattern (`host(r'', settings.ROOT_URLCONF, name='root')`) is `root`, so you need update the settings as `DEFAULT_HOST = 'root'`.
